<?php foreach ($this->posts as $post): /* @var $post Application_Model_Post */ ?>

    <div class="row">    
        <div class="col-md-2 col-sm-3 text-center">
            <a class="story-img" href="#"><img src="http://placehold.it/100" style="width:100px;height:100px" class="img-circle"></a>
        </div>
        <div class="col-md-10 col-sm-9">
            <h3><?= $post->getTitulo() ?></h3>
            <h5><?= $post->getDataDescritiva() ?></h5>
            <div class="row">
                <div class="col-xs-9">

                    <?= $post->getResumo() ?>

                    <p class="lead">
                        <a href="<?php echo $this->url(array("action"=>"mostrar", "id"=>$post->getIdPost())) ?>" class="btn btn-primary">leia Mais</a>
                    </p>
                    
                    <p class="pull-right"><span class="label label-default">keyword</span> <span class="label label-default">tag</span> <span class="label label-default">post</span></p>
                    <ul class="list-inline">
                        <li>
                            <a href="#">2 Days Ago</a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="glyphicon glyphicon-comment"></i> 4 Comments
                            </a>
                        </li>
                        <li>
                            <a href="#"><i class="glyphicon glyphicon-share"></i> 34 Shares</a>
                        </li>
                    </ul>
                </div>
                <div class="col-xs-3"></div>
            </div>
        </div>
    </div>
    <hr>

<?php endforeach; ?>
    
    
<?php
  echo $this->paginationControl(
    $this->posts,
    "Sliding",
    "paginator.phtml"
  );
?>