<!--/stories-->
<?php
	$post = $this->post; /* @var $post Application_Model_Post */
?>

<div class="row">
	<div class="col-md-2 col-sm-3 text-center">
		<a class="story-img" href="#"><img src="http://placehold.it/100"
			style="width: 100px; height: 100px" class="img-circle"></a>
	</div>
	<div class="col-md-10 col-sm-9">
		<h3><?= $post->getTitulo() ?></h3>
		<h5><?= $post->getDataDescritiva() ?></h5>
		<div class="row">
			<div class="col-xs-9">

				<p><?= $post->getDescricao() ?></p>

				<p class="pull-right">
					<span class="label label-default">keyword</span> <span
						class="label label-default">tag</span> <span
						class="label label-default">post</span>
				</p>
				<ul class="list-inline">
					<li><a href="#">2 Days Ago</a></li>
					<li><a href="#"><i class="glyphicon glyphicon-comment"></i> 4
							Comments</a></li>
					<li><a href="#"><i class="glyphicon glyphicon-share"></i> 34 Shares</a></li>
				</ul>
			</div>
		</div>
		

		<div class="row">
			<div class="col-xs-4">
<?	echo $this->form ?>
			</div>
			<div class="col-xs-5">
				<h2>Comentários</h2>

<?	if(count($this->comentarios)): ?>

				<div class="list-group">				
<?		foreach($this->comentarios as $comentario): /* @var $comentario Application_Model_Comentario */ ?>

					<div class="list-group-item">
						<h4 class="list-group-item-heading"><?=$comentario->getNome()?> em <?=$comentario->getData()?></h4>
						<p class="list-group-item-text"><?=$comentario->getComentario()?></p>
					</div>

<?		endforeach; ?>
				</div>

<?	endif; ?>
			</div>
		</div>
		

	</div>
	<!--/stories-->